make_story:
  description: >
    Create an interesting, concise, and coherent story using these vocab words:
    {vocab_words}. Ensure that you use the words properly such that your story
    can be used as comprehensible input.
  expected_output: >
    A short, engaging, and logical story that correctly uses all the 
    following vocab words: {vocab words}. The reader should be able to 
    guess the meanings of the words from context.
  agent: story_maker

make_jokes:
  description: >
    Create original, interesting, and funny jokes (At least 1 for each word). 
    that correctly these vocab words: {vocab_words}. 
  expected_output: >
    A list of jokes with each word being in at least 1 joke. The jokes should
    be funny and act as comprehenisble input, such that the reader and guess
    the meaning of each word from context.
  agent: joke_maker